### ISSUE TITLE
I have something wrong when I try to load weight to train the model

### ISSUE THREAD

**Issue by wnov** [XiaXuehai/faceboxes#17]
I get this when I run trainvisdom.py ,shall I do some preparation before running the script??

Traceback (most recent call last):
  File "E:\My_Project\face_recognition\faceboxes-master\trainvisdom.py", line 112, in <module>
    train()
  File "E:\My_Project\face_recognition\faceboxes-master\trainvisdom.py", line 27, in train
    net.load_state_dict(torch.load('weight/faceboxes.pt'))
  File "C:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FaceBox:
	Unexpected key(s) in state_dict: "bn1.num_batches_tracked", "bn2.num_batches_tracked", "inception1.conv1.1.num_batches_tracked", "inception1.conv2.1.num_batches_tracked", "inception1.conv3.1.num_batches_tracked", "inception1.conv4.1.num_batches_tracked", "inception1.conv5.1.num_batches_tracked", "inception1.conv6.1.num_batches_tracked", "inception1.conv7.1.num_batches_tracked", "inception2.conv1.1.num_batches_tracked", "inception2.conv2.1.num_batches_tracked", "inception2.conv3.1.num_batches_tracked", "inception2.conv4.1.num_batches_tracked", "inception2.conv5.1.num_batches_tracked", "inception2.conv6.1.num_batches_tracked", "inception2.conv7.1.num_batches_tracked", "inception3.conv1.1.num_batches_tracked", "inception3.conv2.1.num_batches_tracked", "inception3.conv3.1.num_batches_tracked", "inception3.conv4.1.num_batches_tracked", "inception3.conv5.1.num_batches_tracked", "inception3.conv6.1.num_batches_tracked", "inception3.conv7.1.num_batches_tracked", "conv3_1.1.num_batches_tracked", "conv3_2.1.num_batches_tracked", "conv4_1.1.num_batches_tracked", "conv4_2.1.num_batches_tracked".

**Comment by XiaXuehai** [comment]
Maybe your pytorch version is different from mine.
